source 'https://rubygems.org'
gem 'ruby-filemagic'
gem 'sanitize'
gem 'sinatra'
gem 'sinatra-browserid', :git => 'https://github.com/sch1zo/sinatra-browserid'
gem 'taglib-ruby'
gem 'nokogiri'
gem 'puma'
gem 'sqlite3'
gem 'rubyzip'
